---
# Master playbook that imports all specific playbooks
- name: Import Gateway Playbook
  ansible.builtin.import_playbook: gateways.yml

- name: Import Workstation Playbook
  ansible.builtin.import_playbook: workstations.yml
