---
- name: Restart_casaos_services
  ansible.builtin.shell: |
    cd /DATA/AppData && \
    for compose_file in */docker-compose.yml; do
      if [ -f "$compose_file" ]; then
        docker-compose -f "$compose_file" restart
      fi
    done
  changed_when: true
  become: true
