name: big-bear-adguard-home-host
services:
  big-bear-adguard-home-host:
    cpu_shares: 1024
    command: []
    container_name: adguard-home-hostmode-host
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    hostname: adguard-home-hostmode-host
    image: adguard/adguardhome:v0.107.71
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-adguard-home-host/data/work
        target: /opt/adguardhome/work
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-adguard-home-host/data/conf
        target: /opt/adguardhome/conf
        bind:
          create_host_path: true
      - type: bind
        source: "{{ pki_output_folder }}/adguard.crt"
        target: /opt/adguardhome/certs/server.crt
        bind:
          create_host_path: true
      - type: bind
        source: "{{ pki_output_folder }}/adguard.key"
        target: /opt/adguardhome/certs/server.key
        bind:
          create_host_path: true
    x-casaos:
      volumes:
        - container: /opt/adguardhome/work
          description:
            en_us: "Container Path: /opt/adguardhome/work"
        - container: /opt/adguardhome/conf
          description:
            en_us: "Container Path: /opt/adguardhome/conf"
    ports: []
    devices: []
    cap_add: []
    environment: []
    network_mode: host
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Use if you're going to use Adguard Home as a DHCP server. AdGuard Home is
      a network-wide software for blocking ads and tracking. After you set it
      up, it'll cover all your home devices, and you won't need any client-side
      software for that. Learn more on our official Github repository.
  developer: AdGuardTeam
  hostname: guard.bastion
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
  index: /
  is_uncontrolled: false
  main: big-bear-adguard-home-host
  port_map: "443"
  scheme: https
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-3.png
  store_app_id: big-bear-adguard-home-host
  tagline:
    en_us: Network Mode is host. Network-wide ads & trackers blocking DNS server.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/thumbnail.png
  tips:
    before_install:
      en_us: >
        Run this script:


        ```

        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-adguard-home-config/run.sh)"

        ```


        After running this script, you need to restart the container.
  title:
    custom: ""
    en_us: AdGuard Home (HOST)
    