name: big-bear-upsnap
services:
  big-bear-upsnap:
    cpu_shares: 256
    command: []
    container_name: Upsnap-Host
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    hostname: Upsnap-Host
    image: ghcr.io/seriousm4x/upsnap:5.2.4
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/upsnap.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-upsnap/pb/data
        target: /app/pb_data
        bind:
          create_host_path: true
      - type: bind
        source: "{{ pki_output_folder }}/upsnap.crt"
        target: /app/certs/server.crt
        bind:
          create_host_path: true
      - type: bind
        source: "{{ pki_output_folder }}/upsnap.key"
        target: /app/certs/server.key
        bind:
          create_host_path: true
    x-casaos:
      volumes:
        - container: /app/pb_data
          description:
            en_us: "Container Path: /app/pb_data"
    ports: []
    devices: []
    cap_add: []
    environment:
      - SSL_CERT=/app/certs/server.crt
      - SSL_KEY=/app/certs/server.key
      - HTTPS_ENABLED=true
    network_mode: host
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: A simple wake on lan web app written with SvelteKit, Go and PocketBase.
  developer: seriousm4x
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/upsnap.png
  index: /
  is_uncontrolled: false
  main: big-bear-upsnap
  port_map: "8443"
  scheme: https
  store_app_id: big-bear-upsnap
  tagline:
    en_us: Upsnap
  thumbnail: ""
  tips:
    before_install:
      en_us: >
        Read this before installing:
        https://community.bigbeartechworld.com/t/added-upsnap-to-bigbearcasaos/2279?u=dragonfire1119
  title:
    custom: ""
    en_us: Upsnap
