system_users:
  - username: gatekeeper
    groups: sudo,docker
    shell: /bin/bash
    state: present

  - username: vanguard
    groups: sudo,docker
    shell: /bin/bash
    state: present

system_groups:
  - "sudo"
  - "docker"
