- name: Setup Culture
  ansible.builtin.include_tasks:
    file: setup_culture.yml
  tags:
    - common
    - timezone
    - locale
    - culture

- name: Setup Packages
  ansible.builtin.include_tasks:
    file: setup_packages.yml
  tags:
    - common
    - packages

- name: Setup Power Management
  ansible.builtin.include_tasks:
    file: setup_power_management.yml
  tags:
    - common
