- name: "Install Docker"
  ansible.builtin.include_role:
    name: geerlingguy.docker
  tags:
    - docker

- name: Install Python Docker SDK (Required for Ansible modules)
  ansible.builtin.package:
    name: python3-docker
    state: present
  tags:
    - docker

- name: Create Folder Just for Composes
  ansible.builtin.file:
    path: /composes
    state: directory
    mode: '0755'
  tags:
    - docker
